In [10]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [11]:
path='iris.csv'
rd=pd.read_csv(path)
df=pd.DataFrame(rd)
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [12]:
x=df['Species'].unique()
print(x)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

In [13]:

df1=df.where(df['Species']=='Iris-setosa')
df1=df1.dropna()
df1.head()

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0  1.0            5.1           3.5            1.4           0.2  Iris-setosa
1  2.0            4.9           3.0            1.4           0.2  Iris-setosa
2  3.0            4.7           3.2            1.3           0.2  Iris-setosa
3  4.0            4.6           3.1            1.5           0.2  Iris-setosa
4  5.0            5.0           3.6            1.4           0.2  Iris-setosa

In [14]:
df2=df.where(df['Species']=='Iris-versicolor')
df2=df2.dropna()
df2.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
50,51.0,7.0,3.2,4.7,1.4,Iris-versicolor
51,52.0,6.4,3.2,4.5,1.5,Iris-versicolor
52,53.0,6.9,3.1,4.9,1.5,Iris-versicolor
53,54.0,5.5,2.3,4.0,1.3,Iris-versicolor
54,55.0,6.5,2.8,4.6,1.5,Iris-versicolor

In [15]:
df3=df.where(df['Species']=='Iris-virginica')
df3=df3.dropna()
df3.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
100,101.0,6.3,3.3,6.0,2.5,Iris-virginica
101,102.0,5.8,2.7,5.1,1.9,Iris-virginica
102,103.0,7.1,3.0,5.9,2.1,Iris-virginica
103,104.0,6.3,2.9,5.6,1.8,Iris-virginica
104,105.0,6.5,3.0,5.8,2.2,Iris-virginica

In [16]:
import random
r=df1['Id'].values
r=list(r)
test_1=random.choice(r)
df_t1=df1.where(df1['Id']==test_1)
df1=df1.drop(test_1-1)
print(df1.shape)
df_t1=df_t1.dropna()
df_t1

(49, 6)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
30,31.0,4.8,3.1,1.6,0.2,Iris-setosa

In [17]:
r=df2['Id'].values
r=list(r)
test_2=random.choice(r)
print(test_2)
df_t2=df2.where(df2['Id']==test_2)
df2=df2.drop(test_2-1)
print(df2.shape)
df_t2=df_t2.dropna()
df_t2

91.0
(49, 6)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
90,91.0,5.5,2.6,4.4,1.2,Iris-versicolor

In [18]:

r=df3['Id'].values
r=list(r)
test_3=random.choice(r)
print(test_3)
df_t3=df3.where(df3['Id']==test_3)
df3=df3.drop(test_3-1)
print(df3.shape)
df_t3=df_t3.dropna()
df_t3

110.0
(49, 6)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
109,110.0,7.2,3.6,6.1,2.5,Iris-virginica

In [19]:
m1=df1.mean()
m2=df2.mean()
m3=df3.mean()
print(m1,m2,m3)

Id               25.387755
SepalLengthCm     5.010204
SepalWidthCm      3.424490
PetalLengthCm     1.461224
PetalWidthCm      0.244898
dtype: float64 Id               75.183673
SepalLengthCm     5.944898
SepalWidthCm      2.773469
PetalLengthCm     4.257143
PetalWidthCm      1.328571
dtype: float64 Id               125.816327
SepalLengthCm      6.575510
SepalWidthCm       2.961224
PetalLengthCm      5.540816
PetalWidthCm       2.016327
dtype: float64

C:\Users\K NONIESH REDDY\AppData\Local\Temp\ipykernel_8216\3911778383.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  m1=df1.mean()
C:\Users\K NONIESH REDDY\AppData\Local\Temp\ipykernel_8216\3911778383.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  m2=df2.mean()
C:\Users\K NONIESH REDDY\AppData\Local\Temp\ipykernel_8216\3911778383.py:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  m3=df3.mean()

In [20]:
c1=df1.cov()
c2=df2.cov()
c3=df3.cov()
print(c1,c2,c3)

                       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Id             216.284014      -0.151956     -0.340944       0.121599
SepalLengthCm   -0.151956       0.125935      0.100995       0.017071
SepalWidthCm    -0.340944       0.100995      0.146054       0.012844
PetalLengthCm    0.121599       0.017071      0.012844       0.030340
PetalWidthCm     0.144728       0.010574      0.011378       0.005944

               PetalWidthCm
Id                 0.144728
SepalLengthCm      0.010574
SepalWidthCm       0.011378
PetalLengthCm      0.005944
PetalWidthCm       0.011692                          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Id             211.819728      -1.923002     -0.326276      -1.371131
SepalLengthCm   -1.923002       0.267942      0.085383       0.188006
SepalWidthCm    -0.326276       0.085383      0.099906       0.084881
PetalLengthCm   -1.371131       0.188006      0.084881       0.225000
PetalWidthCm    -0.455357       0.055774      0.041607       0.075000

               PetalWidthCm
Id                -0.455357
SepalLengthCm      0.055774
SepalWidthCm       0.041607
PetalLengthCm      0.075000
PetalWidthCm       0.039583                          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Id             211.819728       0.082908      0.834396      -1.496514
SepalLengthCm    0.082908       0.404804      0.087572       0.302479
SepalWidthCm     0.834396       0.087572      0.097840       0.065574
PetalLengthCm   -1.496514       0.302479      0.065574       0.304549
PetalWidthCm     0.305145       0.043950      0.042313       0.044320

               PetalWidthCm
Id                 0.305145
SepalLengthCm      0.043950
SepalWidthCm       0.042313
PetalLengthCm      0.044320
PetalWidthCm       0.072228

C:\Users\K NONIESH REDDY\AppData\Local\Temp\ipykernel_8216\1043069621.py:1: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  c1=df1.cov()
C:\Users\K NONIESH REDDY\AppData\Local\Temp\ipykernel_8216\1043069621.py:2: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  c2=df2.cov()
C:\Users\K NONIESH REDDY\AppData\Local\Temp\ipykernel_8216\1043069621.py:3: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  c3=df3.cov()

In [21]:
m1=list(m1)
m2=list(m2)
m3=list(m3)
print(m1,m2,m3)

[25.387755102040817, 5.010204081632653, 3.4244897959183676, 1.4612244897959186, 0.24489795918367346] [75.18367346938776, 5.944897959183674, 2.7734693877551027, 4.257142857142857, 1.3285714285714285] [125.81632653061224, 6.575510204081632, 2.961224489795918, 5.540816326530614, 2.0163265306122446]

In [22]:
r1=df1.iloc[0]
x1=r1.values
x1=list(x1)
x1.remove('Iris-setosa')
print(x1)

[1.0, 5.1, 3.5, 1.4, 0.2]

In [23]:
r2=df2.iloc[0]
x2=r2.values
x2=list(x2)
x2.remove('Iris-versicolor')
print(x2)

[51.0, 7.0, 3.2, 4.7, 1.4]

In [24]:
r3=df3.iloc[0]
x3=r3.values
x3=list(x3)
x3.remove('Iris-virginica')
print(x3)

[101.0, 6.3, 3.3, 6.0, 2.5]

In [25]:
c1=np.array(c1)
c2=np.array(c2)
c3=np.array(c3)
print(c1,c2,c3)

[[ 2.16284014e+02 -1.51955782e-01 -3.40943878e-01  1.21598639e-01
   1.44727891e-01]
 [-1.51955782e-01  1.25935374e-01  1.00994898e-01  1.70705782e-02
   1.05739796e-02]
 [-3.40943878e-01  1.00994898e-01  1.46054422e-01  1.28443878e-02
   1.13775510e-02]
 [ 1.21598639e-01  1.70705782e-02  1.28443878e-02  3.03401361e-02
   5.94387755e-03]
 [ 1.44727891e-01  1.05739796e-02  1.13775510e-02  5.94387755e-03
   1.16921769e-02]] [[ 2.11819728e+02 -1.92300170e+00 -3.26275510e-01 -1.37113095e+00
  -4.55357143e-01]
 [-1.92300170e+00  2.67942177e-01  8.53826531e-02  1.88005952e-01
   5.57738095e-02]
 [-3.26275510e-01  8.53826531e-02  9.99064626e-02  8.48809524e-02
   4.16071429e-02]
 [-1.37113095e+00  1.88005952e-01  8.48809524e-02  2.25000000e-01
   7.50000000e-02]
 [-4.55357143e-01  5.57738095e-02  4.16071429e-02  7.50000000e-02
   3.95833333e-02]] [[ 2.11819728e+02  8.29081633e-02  8.34396259e-01 -1.49651361e+00
   3.05144558e-01]
 [ 8.29081633e-02  4.04804422e-01  8.75722789e-02  3.02478741e-01
   4.39498299e-02]
 [ 8.34396259e-01  8.75722789e-02  9.78401361e-02  6.55739796e-02
   4.23129252e-02]
 [-1.49651361e+00  3.02478741e-01  6.55739796e-02  3.04549320e-01
   4.43197279e-02]
 [ 3.05144558e-01  4.39498299e-02  4.23129252e-02  4.43197279e-02
   7.22278912e-02]]

In [40]:
from scipy.linalg import inv
def mahalobis_distance(x,c,m):
    sub=np.subtract(x,m)
    subt=sub.T
    C1=inv(c)
    d=np.sqrt(np.dot(np.dot(subt,C1),sub))
    return d
x_t=[x1,x2,x3]
c_t=[c1,c2,c3]
m_t=[m1,m2,m3]
#Calculating for setsosa 
d=[]
classes=['Iris-setosa' ,'Iris-versicolor', 'Iris-virginica']
for z in range(len(x_t)):
    d=[]
    for i,j in zip(c_t,m_t):
        dis=mahalobis_distance(x_t[z],i,j)
        d.append(dis)
    d=np.array(d)
    t=z+1
    print(f"Mahalobis distance for {t} sample")
    print(d)
    r=np.argmin(d)
    r=int(r)
    print("predicted class:",classes[r])
    print("original class:",classes[z])
    print("\n")

Mahalobis distance for 1 sample
[ 1.72602857 12.50407567 19.64792087]
predicted class: Iris-setosa
original class: Iris-setosa


Mahalobis distance for 2 sample
[20.66834082  2.76913807  8.89057945]
predicted class: Iris-versicolor
original class: Iris-versicolor


Mahalobis distance for 3 sample
[30.61512843  7.38799566  3.26026941]
predicted class: Iris-virginica
original class: Iris-virginica